print("escriba su primer nombre:")
nombre1=input()
print("escriba su segundo nombre:")
nombre2=input()
print("escriba su primer apellido:")
apellido1=input()
print("esciba su segundo apellido:")
apellido2=input()
print("escriba su edad:")
edad=input()
print("esciba su año de nacimiento:")
anio=input()
print("nombre completo:" + nombre1 + "" + nombre2 + "" + apellido1 + "" + apellido2)
print("edad: " + edad)
print("año de nacimiento:" + anio)
